/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditUserDialog: typeof import('./src/components/edit-user-dialog.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Overlay: typeof import('./src/components/overlay.vue')['default']
    OverlayComponent: typeof import('./src/components/overlay-component.vue')['default']
    Pagination: typeof import('./src/components/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search-input.vue')['default']
    SkeletonTable: typeof import('./src/components/Skeleton-table.vue')['default']
  }
}
